/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dalea
 */
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class BuscarArticulo extends javax.swing.JFrame {

    /**
     * Creates new form BuscarArticulo
     */
    private UserCRUD crud;
    
    public BuscarArticulo() {
        initComponents();
        this.setTitle("Consultar Artículo");
        UserCRUD crud = new UserCRUD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnBuscarId = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JLabel();
        btnBuscarTodos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtId1 = new javax.swing.JTextField();
        btnBuscarId1 = new javax.swing.JLabel();
        btnEliminarArticulo1 = new javax.swing.JLabel();
        btnRegresar1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("CONSULTAR ARTICULO");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtId.setText("INGRESE ID.");
        txtId.setBorder(null);
        txtId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtIdMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtIdMousePressed(evt);
            }
        });
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnBuscarId.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBuscarId.setForeground(new java.awt.Color(153, 153, 153));
        btnBuscarId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarId.setText("BUSCAR");
        btnBuscarId.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarIdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarIdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarIdMouseExited(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(51, 51, 51));
        btnRegresar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar.setText("REGRESAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });

        btnBuscarTodos.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBuscarTodos.setForeground(new java.awt.Color(153, 153, 153));
        btnBuscarTodos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarTodos.setText("BUSCAR A TODOS");
        btnBuscarTodos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarTodosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarTodosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarTodosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarTodos)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscarId)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarId))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(45, 45, 45))
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("ELIIMINAR ARTICULO");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtId1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtId1.setForeground(new java.awt.Color(153, 153, 153));
        txtId1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtId1.setText("INGRESE ID.");
        txtId1.setBorder(null);
        txtId1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtId1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtId1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtId1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtId1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtId1MousePressed(evt);
            }
        });
        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });

        btnBuscarId1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBuscarId1.setForeground(new java.awt.Color(153, 153, 153));
        btnBuscarId1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnBuscarId1.setText("BUSCAR");
        btnBuscarId1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarId1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarId1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarId1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarId1MouseExited(evt);
            }
        });

        btnEliminarArticulo1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarArticulo1.setForeground(new java.awt.Color(153, 153, 153));
        btnEliminarArticulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEliminarArticulo1.setText("ELIMINAR");
        btnEliminarArticulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarArticulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarArticulo1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarArticulo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarArticulo1MouseExited(evt);
            }
        });

        btnRegresar1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnRegresar1.setForeground(new java.awt.Color(51, 51, 51));
        btnRegresar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegresar1.setText("REGRESAR");
        btnRegresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresar1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar1)
                    .addComponent(btnEliminarArticulo1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnBuscarId1))
                    .addComponent(jLabel3))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarId1))
                .addGap(18, 18, 18)
                .addComponent(btnEliminarArticulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnRegresar1)
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 300));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Artículo", "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 220, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 246, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseClicked
        // TODO add your handling code here:
        String Ing = new String(txtId.getText());
        if(Ing.equals("INGRESE ID.")){
            txtId.setText("");
        }
        txtId.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtIdMouseClicked

    private void txtIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMouseEntered

    private void txtIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMouseExited

    private void txtIdMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdMousePressed
        // TODO add your handling code here:
        String contra = new String(txtId.getText());
        if (contra.equals("INGRESE ID.")) {
            txtId.setText(""); // Limpia solo si está el texto por defecto
        }
        txtId.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtIdMousePressed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBuscarIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIdMouseClicked
        //1.- Obtener el valor del txt
        String idtext = txtId.getText();

        //2.- Validar txt vacío
        if(idtext.isEmpty() || idtext.equals("INGRESE ID.")){
            JOptionPane.showMessageDialog(this, "ERROR, campo vacío!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!idtext.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido (número)","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
    //3.- Búsqueda y llenado de la tabla
    try {
        int id = Integer.parseInt(idtext);
        
        UserCRUD crud = new UserCRUD(); // <-- ¡ESTA LÍNEA ES IMPORTANTE!
        
        ResultSet rs = crud.buscarPorIDArticulo(id);
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        if(rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("id_articulo"),
                rs.getString("Nombre_articulo"),
                rs.getInt("cantidad_articulo")
            });
        }
    } catch(SQLException e) {
        System.out.print("Error al llenar la tabla: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBuscarIdMouseClicked

    private void btnBuscarIdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIdMouseEntered
        // TODO add your handling code here:
        btnBuscarId.setForeground(new java.awt.Color(0,102,102));
    }//GEN-LAST:event_btnBuscarIdMouseEntered

    private void btnBuscarIdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarIdMouseExited
        // TODO add your handling code here:
        btnBuscarId.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnBuscarIdMouseExited

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        menuAdminArticulos MAA = new menuAdminArticulos();
        MAA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        // TODO add your handling code here:
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        // TODO add your handling code here:
        btnRegresar.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void txtId1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtId1MouseClicked
        // TODO add your handling code here:
        String Ing = new String(txtId.getText());
        if(Ing.equals("INGRESE ID.")){
            txtId.setText("");
        }
        txtId.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtId1MouseClicked

    private void txtId1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtId1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1MouseEntered

    private void txtId1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtId1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1MouseExited

    private void txtId1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtId1MousePressed
        // TODO add your handling code here:
        String contra = new String(txtId.getText());
        if (contra.equals("INGRESE ID")) {
            txtId.setText(""); // Limpia solo si está el texto por defecto
        }
        txtId.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_txtId1MousePressed

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void btnBuscarId1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarId1MouseClicked
        //1.- Obtener el valor del txt
        String idtext = txtId.getText();

        //2.- Validar txt vacio
        if(idtext.isEmpty()){
            JOptionPane.showMessageDialog(this, "ERROR, campo vacío!","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }

        //3.- Búsqueda y llenado de la tabla
        try{
            int id = Integer.parseInt(idtext);
            ResultSet rs = crud.buscarPorIDArticulo(id);
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            if(rs.next()){
                modelo.addRow(new Object[]{rs.getInt("id_articulo"),rs.getString("Nombre_articulo"),rs.getInt("cantidad_articulo")});
            }
        }
        catch(SQLException e){
            System.out.print("Error al llenar la tabla: "+e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarId1MouseClicked

    private void btnBuscarId1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarId1MouseEntered
        // TODO add your handling code here:
        btnBuscarId.setForeground(new java.awt.Color(0,102,102));
    }//GEN-LAST:event_btnBuscarId1MouseEntered

    private void btnBuscarId1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarId1MouseExited
        // TODO add your handling code here:
        btnBuscarId.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnBuscarId1MouseExited

    private void btnEliminarArticulo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarArticulo1MouseClicked
        // TODO add your handling code here:
        String id_articuloText = txtId.getText();
        int id_articuloT = Integer.parseInt(id_articuloText);

        if(id_articuloText.isEmpty()){
            JOptionPane.showMessageDialog(this, "Campo vacío!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int op = JOptionPane.showOptionDialog(null, "¿Seguro de eliminar al usuario?", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si", "No"}, EXIT_ON_CLOSE);
        if(op == 0){
            UserCRUD crud = new UserCRUD();
            boolean eliminar = crud.EliminarPorIDArticulo(id_articuloT);
            if(eliminar){
                JOptionPane.showMessageDialog(this, "Usuario Eliminado Exitosamente!", "Conexión Exitosa", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No existe un registro con tal ID!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if(op == 1){
            JOptionPane.showMessageDialog(null, "Operación cancelada!");
        }
    }//GEN-LAST:event_btnEliminarArticulo1MouseClicked

    private void btnEliminarArticulo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarArticulo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarArticulo1MouseEntered

    private void btnEliminarArticulo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarArticulo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarArticulo1MouseExited

    private void btnRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        menuAdminArticulos MAA = new menuAdminArticulos();
        MAA.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresar1MouseClicked

    private void btnRegresar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseEntered
        // TODO add your handling code here:
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnRegresar1MouseEntered

    private void btnRegresar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresar1MouseExited
        // TODO add your handling code here:
        btnRegresar.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_btnRegresar1MouseExited

    private void btnBuscarTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarTodosMouseClicked
        // TODO add your handling code here:
        UserCRUD crud = new UserCRUD();

        ResultSet todos = crud.obtenerTodosArticulo();
        DefaultTableModel modeloT = (DefaultTableModel) jTable1.getModel();
        modeloT.setRowCount(0);
        
    try {
        while (todos.next()) {
            modeloT.addRow(new Object[]{
                todos.getInt("id_articulo"),
                todos.getString("Nombre_articulo"),
                todos.getInt("cantidad_articulo")
            });
        }
    } catch (SQLException e) {
        System.out.print("Error al llenar la tabla: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBuscarTodosMouseClicked

    private void btnBuscarTodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarTodosMouseEntered
        // TODO add your handling code here:
        btnBuscarTodos.setForeground(new java.awt.Color(0,102,102));
    }//GEN-LAST:event_btnBuscarTodosMouseEntered

    private void btnBuscarTodosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarTodosMouseExited
        // TODO add your handling code here:
        btnBuscarTodos.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnBuscarTodosMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBuscarId;
    private javax.swing.JLabel btnBuscarId1;
    private javax.swing.JLabel btnBuscarTodos;
    private javax.swing.JLabel btnEliminarArticulo1;
    private javax.swing.JLabel btnRegresar;
    private javax.swing.JLabel btnRegresar1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    // End of variables declaration//GEN-END:variables
}
