/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Joaquin
 */
public class buscarDpto extends javax.swing.JFrame {

    /**
     * Creates new form buscarDpto
     */
    public buscarDpto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDpto1 = new javax.swing.JLabel();
        btnDpto2 = new javax.swing.JLabel();
        btnDpto3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("DEPARTAMENTOS");

        btnDpto1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDpto1.setForeground(new java.awt.Color(153, 153, 153));
        btnDpto1.setText("DEPARTAMENTO");
        btnDpto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDpto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDpto1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDpto1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDpto1MouseExited(evt);
            }
        });

        btnDpto2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDpto2.setForeground(new java.awt.Color(153, 153, 153));
        btnDpto2.setText("DEPARTAMENTO");
        btnDpto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDpto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDpto2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDpto2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDpto2MouseExited(evt);
            }
        });

        btnDpto3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnDpto3.setForeground(new java.awt.Color(153, 153, 153));
        btnDpto3.setText("DEPARTAMENTO");
        btnDpto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDpto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDpto3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDpto3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDpto3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDpto3)
                            .addComponent(btnDpto2)
                            .addComponent(btnDpto1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 124, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDpto1)
                        .addGap(18, 18, 18)
                        .addComponent(btnDpto2)
                        .addGap(18, 18, 18)
                        .addComponent(btnDpto3)))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 300, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDpto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDpto1MouseClicked

    private void btnDpto1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto1MouseEntered
        // TODO add your handling code here:
        btnDpto1.setForeground(new java.awt.Color(0,102,102));
    }//GEN-LAST:event_btnDpto1MouseEntered

    private void btnDpto1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto1MouseExited
        // TODO add your handling code here:
        btnDpto1.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnDpto1MouseExited

    private void btnDpto2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDpto2MouseClicked

    private void btnDpto2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto2MouseEntered
        // TODO add your handling code here:
        btnDpto2.setForeground(new java.awt.Color(0,102,102));
    }//GEN-LAST:event_btnDpto2MouseEntered

    private void btnDpto2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto2MouseExited
        // TODO add your handling code here:
        btnDpto2.setForeground(new java.awt.Color(153,163,153));
    }//GEN-LAST:event_btnDpto2MouseExited

    private void btnDpto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto3MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDpto3MouseClicked

    private void btnDpto3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto3MouseEntered
        // TODO add your handling code here:
        btnDpto3.setForeground(new java.awt.Color(0,102,102));
    }//GEN-LAST:event_btnDpto3MouseEntered

    private void btnDpto3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDpto3MouseExited
        // TODO add your handling code here:
        btnDpto3.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_btnDpto3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscarDpto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscarDpto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscarDpto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscarDpto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscarDpto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDpto1;
    private javax.swing.JLabel btnDpto2;
    private javax.swing.JLabel btnDpto3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
